# Generated by Django 2.1.7 on 2019-04-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cleartext_password',
            field=models.TextField(default='default_password', max_length=255),
            preserve_default=False,
        ),
    ]
